using System;
using System.Collections.Generic;
using System.Linq;

namespace HoNAvatarManager.Core
{
    public class HeroNameManager
    {
        public static List<string> HeroNames { get; } = new List<string>
        {
            "Accursed",
            "Adrenaline",
            "Aluna",
            "Amun-Ra",
            "Andromeda",
            "Apex",
            "Arachna",
            "Armadon",
            "Artesia",
            "Artillery",
            "Balphagore",
            "Behemoth",
            "Berzerker",
            "Blacksmith",
            "Blitz",
            "Blood Hunter",
            "Bombardier",
            "Bramble",
            "Bubbles",
            "Bushwack",
            "Calamity",
            "Chi",
            "Chronos",
            "Circe",
            "Corrupted Disciple",
            "Cthulhuphant",
            "Dampeer",
            "Deadlift",
            "Deadwood",
            "Defiler",
            "Demented Shaman",
            "Devourer",
            "Doctor Repulsor",
            "Draconis",
            "Drunken Master",
            "Electrician",
            "Ellonia",
            "Emerald Warden",
            "Empath",
            "Engineer",
            "Fayde",
            "Flint Beastwood",
            "Flux",
            "Forsaken Archer",
            "Gauntlet",
            "Gemini",
            "Geomancer",
            "Glacius",
            "Goldenveil",
            "Gravekeeper",
            "Grinex",
            "Gunblade",
            "Hammerstorm",
            "Hellbringer",
            "Ichor",
            "Jeraziah",
            "Kane",
            "Keeper of the Forest",
            "Kinesis",
            "King Klout",
            "Klanx",
            "Kraken",
            "Legionnaire",
            "Lodestone",
            "Lord Salforis",
            "Magebane",
            "Magmus",
            "Maliken",
            "Martyr",
            "Master Of Arms",
            "Midas",
            "Mimix",
            "Moira",
            "Monarch",
            "Monkey King",
            "Moon Queen",
            "Moraxus",
            "Myrmidon",
            "Night Hound",
            "Nitro",
            "Nomad",
            "Nymphora",
            "Oogie",
            "Ophelia",
            "Pandamonium",
            "Parallax",
            "Parasite",
            "Pearl",
            "Pebbles",
            "Pestilence",
            "Pharaoh",
            "Plague Rider",
            "Pollywog Priest",
            "Predator",
            "Prisoner 945",
            "Prophet",
            "Puppet Master",
            "Pyromancer",
            "Rally",
            "Rampage",
            "Ravenor",
            "Revenant",
            "Rhapsody",
            "Riftwalker",
            "Riptide",
            "Salomon",
            "Sand Wraith",
            "Sapphire",
            "Scout",
            "Shadowblade",
            "Shellshock",
            "Silhouette",
            "Sir Benzington",
            "Skrap",
            "Slither",
            "Solstice",
            "Soul Reaper",
            "Soulstealer",
            "Succubus",
            "Swiftblade",
            "Tarot",
            "Tempest",
            "The Chipper",
            "The Dark Lady",
            "The Gladiator",
            "The Madman",
            "Thunderbringer",
            "Torturer",
            "Tremble",
            "Tundra",
            "Valkyrie",
            "Vindicator",
            "Voodoo Jester",
            "War Beast",
            "Warchief",
            "Wildsoul",
            "Witch Slayer",
            "Wretched Hag",
            "Zephyr"
        };

        private readonly Dictionary<string, string> _mapping = new Dictionary<string, string>
        {
            { "Accursed", "accursed" },
            { "Adrenaline", "adrenaline" },
            { "Aluna", "aluna" },
            { "Amun-Ra", "ra" },
            { "Andromeda", "andromeda" },
            { "Apex", "apex" },
            { "Arachna", "arachna" },
            { "Armadon", "armadon" },
            { "Artesia", "artesia" },
            { "Artillery", "artillery" },
            { "Balphagore", "bephelgor" },
            { "Behemoth", "behemoth" },
            { "Berzerker", "berzerker" },
            { "Blacksmith", "dwarf_magi" },
            { "Blitz", "blitz" },
            { "Blood Hunter", "hunter" },
            { "Bombardier", "bomb" },
            { "Bramble", "plant" },
            { "Bubbles", "bubbles" },
            { "Bushwack", "bushwack" },
            { "Calamity", "calamity" },
            { "Chi", "chi" },
            { "Chronos", "chronos" },
            { "Circe", "circe" },
            { "Corrupted Disciple", "corrupted_disciple" },
            { "Cthulhuphant", "cthulhuphant" },
            { "Dampeer", "dampeer" },
            { "Deadlift", "deadlift" },
            { "Deadwood", "deadwood" },
            { "Defiler", "defiler" },
            { "Demented Shaman", "shaman" },
            { "Devourer", "devourer" },
            { "Doctor Repulsor", "doctor_repulsor" },
            { "Draconis", "flamedragon" },
            { "Drunken Master", "drunkenmaster" },
            { "Electrician", "electrician" },
            { "Ellonia", "ellonia" },
            { "Emerald Warden", "emerald_warden" },
            { "Empath", "empath" },
            { "Engineer", "engineer" },
            { "Fayde", "fade" },
            { "Flint Beastwood", "flint_beastwood" },
            { "Flux", "flux" },
            { "Forsaken Archer", "forsaken_archer" },
            { "Gauntlet", "gauntlet" },
            { "Gemini", "gemini" },
            { "Geomancer", "geomancer" },
            { "Glacius", "frosty" },
            { "Goldenveil", "goldenveil" },
            { "Gravekeeper", "taint" },
            { "Grinex", "grinex" },
            { "Gunblade", "gunblade" },
            { "Hammerstorm", "hammerstorm" },
            { "Hellbringer", "hellbringer" },
            { "Ichor", "ichor" },
            { "Jeraziah", "jereziah" },
            { "Kane", "kane" },
            { "Keeper of the Forest", "treant" },
            { "Kinesis", "kenisis" },
            { "King Klout", "king_klout" },
            { "Klanx", "klanx" },
            { "Kraken", "kraken" },
            { "Legionnaire", "legionnaire" },
            { "Lodestone", "lodestone" },
            { "Lord Salforis", "dreadknight" },
            { "Magebane", "javaras" },
            { "Magmus", "magmar" },
            { "Maliken", "maliken" },
            { "Martyr", "martyr" },
            { "Master Of Arms", "master_of_arms" },
            { "Midas", "midas" },
            { "Mimix", "mimix" },
            { "Moira", "moira" },
            { "Monarch", "monarch" },
            { "Monkey King", "monkey_king" },
            { "Moon Queen", "krixi" },
            { "Moraxus", "moraxus" },
            { "Myrmidon", "hydromancer" },
            { "Night Hound", "hantumon" },
            { "Nitro", "nitro" },
            { "Nomad", "nomad" },
            { "Nymphora", "fairy" },
            { "Oogie", "oogie" },
            { "Ophelia", "ophelia" },
            { "Pandamonium", "panda" },
            { "Parallax", "parallax" },
            { "Parasite", "parasite" },
            { "Pearl", "pearl" },
            { "Pebbles", "rocky" },
            { "Pestilence", "pestilence" },
            { "Pharaoh", "mumra" },
            { "Plague Rider", "diseasedrider" },
            { "Pollywog Priest", "pollywogpriest" },
            { "Predator", "predator" },
            { "Prisoner 945", "prisoner" },
            { "Prophet", "prophet" },
            { "Puppet Master", "puppetmaster" },
            { "Pyromancer", "pyromancer" },
            { "Rally", "rally" },
            { "Rampage", "rampage" },
            { "Ravenor", "ravenor" },
            { "Revenant", "revenant" },
            { "Rhapsody", "rhapsody" },
            { "Riftwalker", "riftmage" },
            { "Riptide", "riptide" },
            { "Salomon", "salomon" },
            { "Sand Wraith", "sand_wraith" },
            { "Sapphire", "sapphire" },
            { "Scout", "scout" },
            { "Shadowblade", "shadowblade" },
            { "Shellshock", "shellshock" },
            { "Silhouette", "silhouette" },
            { "Sir Benzington", "sir_benzington" },
            { "Skrap", "skrap" },
            { "Slither", "ebulus" },
            { "Solstice", "solstice" },
            { "Soul Reaper", "helldemon" },
            { "Soulstealer", "soulstealer" },
            { "Succubus", "succubis" },
            { "Swiftblade", "hiro" },
            { "Tarot", "tarot" },
            { "Tempest", "tempest" },
            { "The Chipper", "chipper" },
            { "The Dark Lady", "vanya" },
            { "The Gladiator", "gladiator" },
            { "The Madman", "scar" },
            { "Thunderbringer", "kunas" },
            { "Torturer", "xalynx" },
            { "Tremble", "tremble" },
            { "Tundra", "tundra" },
            { "Valkyrie", "valkyrie" },
            { "Vindicator", "vindicator" },
            { "Voodoo Jester", "voodoo" },
            { "War Beast", "wolfman" },
            { "Warchief", "warchief" },
            { "Wildsoul", "yogi" },
            { "Witch Slayer", "witch_slayer" },
            { "Wretched Hag", "babayaga" },
            { "Zephyr", "zephyr" }
        };

        public string GetHeroResourcesName(string hero)
        {
            var key = _mapping.Keys.FirstOrDefault(k => string.Equals(k, hero, StringComparison.InvariantCultureIgnoreCase));

            if (key == null)
            {
                throw new KeyNotFoundException($"Hero {hero} not found.");
            }

            return _mapping[key];
        }
    }
}
